module: sockets
version: 1
runtime: custom
api_version: 1
vm: true

manual_scaling:
  instances: 1

vm_settings:
  machine_type: f1-micro

vm_health_check:
  enable_health_check: False

handlers:
- url: /.*
  script: main.py